<?php

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'total' => 4547.0,
                'discount' => 0,
                'service_charge' => 120.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 3,
                'created_at' => '2017-11-24 11:23:15',
                'updated_at' => '2018-03-06 16:24:23',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'total' => 4547.0,
                'discount' => 0,
                'service_charge' => 120.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-11-22 11:23:15',
                'updated_at' => '2017-11-22 11:25:27',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'total' => 4465.0,
                'discount' => 0,
                'service_charge' => 80.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-11-24 17:07:12',
                'updated_at' => '2017-11-24 17:07:47',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 1,
                'total' => 1971.0,
                'discount' => 0,
                'service_charge' => 60.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-11-24 17:10:11',
                'updated_at' => '2017-11-24 17:10:46',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'total' => 3297.0,
                'discount' => 0,
                'service_charge' => 60.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-07 06:32:48',
                'updated_at' => '2017-12-07 06:32:53',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 1,
                'total' => 2154.0,
                'discount' => 0,
                'service_charge' => 40.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 1,
                'created_at' => '2017-12-09 01:26:45',
                'updated_at' => '2017-12-09 01:26:45',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 1,
                'total' => 3429.0,
                'discount' => 0,
                'service_charge' => 60.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-11 23:53:24',
                'updated_at' => '2017-12-11 23:55:51',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 5,
                'total' => 200.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => 'h',
                'barangay' => 'j',
                'city' => 'j',
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-12 01:44:40',
                'updated_at' => '2017-12-12 01:44:50',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 5,
                'total' => 180.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => 'g',
                'barangay' => 'g',
                'city' => 'g',
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 1,
                'created_at' => '2017-12-12 01:47:11',
                'updated_at' => '2017-12-12 01:47:11',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 1,
                'total' => 3429.0,
                'discount' => 0,
                'service_charge' => 40.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-12 01:58:24',
                'updated_at' => '2017-12-12 01:58:36',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 1,
                'total' => 300.0,
                'discount' => 0,
                'service_charge' => 40.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-12 02:01:01',
                'updated_at' => '2017-12-12 02:01:10',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 6,
                'total' => 300.0,
                'discount' => 0,
                'service_charge' => 40.0,
                'tax' => 0.0,
                'firstname' => 'Marc',
                'middlename' => NULL,
                'lastname' => 'Amaro',
                'street' => 'Eagle Ave',
                'barangay' => 'Putatan',
                'city' => 'Muntinlupa',
                'state' => 'Metro Manila',
                'contact' => '09175851290',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-12 02:12:01',
                'updated_at' => '2017-12-12 02:20:51',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 6,
                'total' => 290.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Marc',
                'middlename' => NULL,
                'lastname' => 'Amaro',
                'street' => 'ea',
                'barangay' => 'Putatan',
                'city' => 'Muntinlupa',
                'state' => 'Metro Manila',
                'contact' => '09175851290',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-12 02:23:54',
                'updated_at' => '2017-12-12 02:27:50',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 6,
                'total' => 1168.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Marc',
                'middlename' => NULL,
                'lastname' => 'Amaro',
                'street' => 'Eagle Ave',
                'barangay' => 'Putatan',
                'city' => 'Muntinlupa',
                'state' => 'Metro Manila',
                'contact' => '09175851290',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-12 02:29:39',
                'updated_at' => '2017-12-12 03:31:11',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 1,
                'total' => 1143.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-12 03:45:05',
                'updated_at' => '2017-12-12 03:45:13',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 5,
                'total' => 175.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => 'Maryland',
                'barangay' => 'Pinagkaisahan',
                'city' => 'Quezon City',
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-12 04:02:42',
                'updated_at' => '2017-12-12 04:28:40',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 1,
                'total' => 1143.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 1,
                'created_at' => '2017-12-12 04:04:28',
                'updated_at' => '2017-12-12 04:04:28',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 1,
                'total' => 0.0,
                'discount' => 0,
                'service_charge' => 0.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 1,
                'created_at' => '2017-12-12 04:04:50',
                'updated_at' => '2017-12-12 04:04:50',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 6,
                'total' => 2154.0,
                'discount' => 10,
                'service_charge' => 40.0,
                'tax' => 0.0,
                'firstname' => 'Marc',
                'middlename' => NULL,
                'lastname' => 'Amaro',
                'street' => 'B23 L29 Soldiers Hills Village',
                'barangay' => 'Putatan',
                'city' => 'Muntinlupa',
                'state' => 'Metro Manila',
                'contact' => '09175851290',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-12 04:09:25',
                'updated_at' => '2017-12-12 04:17:50',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 5,
                'total' => 180.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => 'Maryland',
                'barangay' => 'Pinagkaisaan',
                'city' => 'Quezon City',
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-12 05:13:54',
                'updated_at' => '2017-12-12 05:16:38',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 1,
                'total' => 3297.0,
                'discount' => 10,
                'service_charge' => 60.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-13 05:03:53',
                'updated_at' => '2017-12-13 05:04:16',
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 1,
                'total' => 1143.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-13 05:05:07',
                'updated_at' => '2017-12-13 05:05:34',
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 1,
                'total' => 1011.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-13 23:08:59',
                'updated_at' => '2017-12-13 23:09:08',
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 1,
                'total' => 1168.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '3',
                'status' => 2,
                'created_at' => '2017-12-14 01:04:28',
                'updated_at' => '2017-12-14 01:04:39',
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 1,
                'total' => 300.0,
                'discount' => 10,
                'service_charge' => 40.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '5',
                'status' => 2,
                'created_at' => '2017-12-14 01:07:55',
                'updated_at' => '2017-12-14 01:08:41',
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 1,
                'total' => 1143.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '6',
                'status' => 2,
                'created_at' => '2017-12-14 03:22:23',
                'updated_at' => '2017-12-14 03:22:45',
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 1,
                'total' => 1168.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '5',
                'status' => 1,
                'created_at' => '2017-12-14 03:40:18',
                'updated_at' => '2017-12-14 03:40:18',
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 1,
                'total' => 1011.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '6',
                'status' => 2,
                'created_at' => '2017-12-14 03:41:07',
                'updated_at' => '2017-12-14 03:41:38',
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 1,
                'total' => 1011.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2017-12-14 03:51:43',
                'updated_at' => '2017-12-14 03:51:53',
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 1,
                'total' => 1143.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 1,
                'created_at' => '2017-12-14 03:52:49',
                'updated_at' => '2017-12-14 03:52:49',
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 1,
                'total' => 110.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '4',
                'status' => 2,
                'created_at' => '2017-12-14 04:48:46',
                'updated_at' => '2017-12-14 04:48:56',
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 1,
                'total' => 300.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '4',
                'status' => 2,
                'created_at' => '2017-12-14 06:29:35',
                'updated_at' => '2017-12-14 06:29:52',
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 1,
                'total' => 90.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '4',
                'status' => 2,
                'created_at' => '2017-12-15 01:08:44',
                'updated_at' => '2017-12-15 01:09:03',
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 1,
                'total' => 80.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '4',
                'status' => 2,
                'created_at' => '2017-12-15 01:55:34',
                'updated_at' => '2017-12-15 01:56:25',
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 1,
                'total' => 1143.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '2',
                'status' => 1,
                'created_at' => '2017-12-20 01:34:29',
                'updated_at' => '2017-12-20 01:34:29',
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 1,
                'total' => 4465.0,
                'discount' => 10,
                'service_charge' => 60.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '55',
                'status' => 1,
                'created_at' => '2017-12-22 07:50:59',
                'updated_at' => '2017-12-22 07:50:59',
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 7,
                'total' => 110.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => '61-D Maryland St.',
                'barangay' => 'Pinagkaisahan',
                'city' => 'Quezon City',
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 1,
                'created_at' => '2017-12-22 07:54:55',
                'updated_at' => '2017-12-22 07:54:55',
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 9,
                'total' => 1371.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'state' => 'Metro Manila',
                'contact' => '123456788',
                'note' => NULL,
                'table_no' => '21',
                'status' => 1,
                'created_at' => '2017-12-22 08:02:32',
                'updated_at' => '2017-12-22 08:02:32',
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 7,
                'total' => 110.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => '3',
                'status' => 1,
                'created_at' => '2017-12-22 08:05:51',
                'updated_at' => '2017-12-22 08:05:51',
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 8,
                'total' => 110.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Rico',
                'middlename' => NULL,
                'lastname' => 'Trinidad',
                'street' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'state' => 'Metro Manila',
                'contact' => '09188273752',
                'note' => NULL,
                'table_no' => '3',
                'status' => 2,
                'created_at' => '2017-12-22 08:33:08',
                'updated_at' => '2017-12-22 08:34:09',
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 10,
                'total' => 150.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'liza',
                'middlename' => NULL,
                'lastname' => 'gil',
                'street' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'state' => 'Metro Manila',
                'contact' => '09163773664',
                'note' => NULL,
                'table_no' => '3',
                'status' => 2,
                'created_at' => '2017-12-23 04:25:18',
                'updated_at' => '2017-12-23 04:25:47',
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 8,
                'total' => 110.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Rico',
                'middlename' => NULL,
                'lastname' => 'Trinidad',
                'street' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'state' => 'Metro Manila',
                'contact' => '09188273752',
                'note' => NULL,
                'table_no' => '3',
                'status' => 2,
                'created_at' => '2017-12-23 04:38:19',
                'updated_at' => '2017-12-23 04:38:56',
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 7,
                'total' => 150.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => '4',
                'status' => 1,
                'created_at' => '2018-01-03 23:28:12',
                'updated_at' => '2018-01-03 23:28:12',
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 7,
                'total' => 0.0,
                'discount' => 10,
                'service_charge' => 0.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => '4',
                'status' => 1,
                'created_at' => '2018-01-03 23:28:12',
                'updated_at' => '2018-01-03 23:28:12',
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 7,
                'total' => 0.0,
                'discount' => 10,
                'service_charge' => 0.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => '4',
                'status' => 1,
                'created_at' => '2018-01-03 23:30:25',
                'updated_at' => '2018-01-03 23:30:25',
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 7,
                'total' => 150.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => '3',
                'status' => 2,
                'created_at' => '2018-01-04 05:37:45',
                'updated_at' => '2018-01-04 05:38:14',
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 1,
                'total' => 5715.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2018-01-04 22:17:47',
                'updated_at' => '2018-01-04 22:17:53',
            ),
            47 => 
            array (
                'id' => 48,
                'user_id' => 1,
                'total' => 1168.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 2,
                'created_at' => '2018-01-05 00:23:23',
                'updated_at' => '2018-01-05 00:26:55',
            ),
            48 => 
            array (
                'id' => 49,
                'user_id' => 1,
                'total' => 1143.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '2',
                'status' => 2,
                'created_at' => '2018-01-05 01:46:06',
                'updated_at' => '2018-01-05 01:46:21',
            ),
            49 => 
            array (
                'id' => 50,
                'user_id' => 1,
                'total' => 2630.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '3',
                'status' => 3,
                'created_at' => '2018-01-05 02:08:39',
                'updated_at' => '2018-01-05 02:08:49',
            ),
            50 => 
            array (
                'id' => 51,
                'user_id' => 1,
                'total' => 1011.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '3',
                'status' => 3,
                'created_at' => '2018-01-05 02:10:36',
                'updated_at' => '2018-01-05 02:10:52',
            ),
            51 => 
            array (
                'id' => 52,
                'user_id' => 7,
                'total' => 130.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => '9',
                'status' => 3,
                'created_at' => '2018-01-05 06:47:29',
                'updated_at' => '2018-01-05 06:47:35',
            ),
            52 => 
            array (
                'id' => 53,
                'user_id' => 1,
                'total' => 1315.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '4',
                'status' => 3,
                'created_at' => '2018-01-05 06:54:35',
                'updated_at' => '2018-01-05 06:55:01',
            ),
            53 => 
            array (
                'id' => 54,
                'user_id' => 1,
                'total' => 0.0,
                'discount' => 10,
                'service_charge' => 0.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '4',
                'status' => 1,
                'created_at' => '2018-01-05 06:55:15',
                'updated_at' => '2018-01-05 06:55:15',
            ),
            54 => 
            array (
                'id' => 55,
                'user_id' => 7,
                'total' => 120.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => '3',
                'status' => 1,
                'created_at' => '2018-01-05 06:58:58',
                'updated_at' => '2018-01-05 06:58:58',
            ),
            55 => 
            array (
                'id' => 56,
                'user_id' => 1,
                'total' => 0.0,
                'discount' => 10,
                'service_charge' => 0.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '4',
                'status' => 1,
                'created_at' => '2018-01-05 07:19:10',
                'updated_at' => '2018-01-05 07:19:10',
            ),
            56 => 
            array (
                'id' => 57,
                'user_id' => 1,
                'total' => 1168.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '3',
                'status' => 1,
                'created_at' => '2018-01-05 07:19:43',
                'updated_at' => '2018-01-05 07:19:43',
            ),
            57 => 
            array (
                'id' => 58,
                'user_id' => 1,
                'total' => 0.0,
                'discount' => 0,
                'service_charge' => 0.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => '3',
                'status' => 1,
                'created_at' => '2018-01-05 07:19:54',
                'updated_at' => '2018-01-05 07:19:54',
            ),
            58 => 
            array (
                'id' => 59,
                'user_id' => 1,
                'total' => 1102.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 1,
                'created_at' => '2018-01-05 07:20:27',
                'updated_at' => '2018-01-05 07:20:27',
            ),
            59 => 
            array (
                'id' => 60,
                'user_id' => 7,
                'total' => 100.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Angelo',
                'middlename' => NULL,
                'lastname' => 'Jugueta',
                'street' => NULL,
                'barangay' => NULL,
                'city' => NULL,
                'state' => 'Metro Manila',
                'contact' => '09178112294',
                'note' => NULL,
                'table_no' => '3',
                'status' => 3,
                'created_at' => '2018-01-06 06:23:57',
                'updated_at' => '2018-01-06 06:24:06',
            ),
            60 => 
            array (
                'id' => 61,
                'user_id' => 1,
                'total' => 1143.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'John',
                'middlename' => NULL,
                'lastname' => 'Doe',
                'street' => 'Road 5 M De Leon',
                'barangay' => 'Santolan',
                'city' => 'Pasig City',
                'state' => 'Metro Manila',
                'contact' => '09164794935',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 1,
                'created_at' => '2018-02-01 05:15:02',
                'updated_at' => '2018-02-01 05:15:02',
            ),
            61 => 
            array (
                'id' => 62,
                'user_id' => 12,
                'total' => 175.0,
                'discount' => 0,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Metrobank',
                'middlename' => NULL,
                'lastname' => 'Kamias',
                'street' => 'K-H St, Kamias Rd',
                'barangay' => 'Diliman',
                'city' => 'Quezon City',
                'state' => 'Metro Manila',
                'contact' => '123456789',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 3,
                'created_at' => '2018-03-06 16:43:56',
                'updated_at' => '2018-03-06 16:44:07',
            ),
            62 => 
            array (
                'id' => 63,
                'user_id' => 12,
                'total' => 180.0,
                'discount' => 10,
                'service_charge' => 20.0,
                'tax' => 0.0,
                'firstname' => 'Metrobank',
                'middlename' => NULL,
                'lastname' => 'Kamias',
                'street' => 'K-H St, Kamias Rd',
                'barangay' => 'Diliman',
                'city' => 'Quezon City',
                'state' => 'Metro Manila',
                'contact' => '123456789',
                'note' => NULL,
                'table_no' => '2',
                'status' => 1,
                'created_at' => '2018-03-06 16:50:02',
                'updated_at' => '2018-03-06 16:50:02',
            ),
            63 => 
            array (
                'id' => 64,
                'user_id' => 12,
                'total' => 0.0,
                'discount' => 0,
                'service_charge' => 0.0,
                'tax' => 0.0,
                'firstname' => 'Metrobank',
                'middlename' => NULL,
                'lastname' => 'Kamias',
                'street' => 'K-H St, Kamias Rd',
                'barangay' => 'Diliman',
                'city' => 'Quezon City',
                'state' => 'Metro Manila',
                'contact' => '123456789',
                'note' => NULL,
                'table_no' => '2',
                'status' => 1,
                'created_at' => '2018-03-06 16:50:16',
                'updated_at' => '2018-03-06 16:50:16',
            ),
            64 => 
            array (
                'id' => 65,
                'user_id' => 12,
                'total' => 0.0,
                'discount' => 0,
                'service_charge' => 0.0,
                'tax' => 0.0,
                'firstname' => 'Metrobank',
                'middlename' => NULL,
                'lastname' => 'Kamias',
                'street' => 'K-H St, Kamias Rd',
                'barangay' => 'Diliman',
                'city' => 'Quezon City',
                'state' => 'Metro Manila',
                'contact' => '123456789',
                'note' => NULL,
                'table_no' => NULL,
                'status' => 1,
                'created_at' => '2018-03-06 16:50:31',
                'updated_at' => '2018-03-06 16:50:31',
            ),
            65 => 
            array (
                'id' => 66,
                'user_id' => 12,
                'total' => 0.0,
                'discount' => 10,
                'service_charge' => 0.0,
                'tax' => 0.0,
                'firstname' => 'Metrobank',
                'middlename' => NULL,
                'lastname' => 'Kamias',
                'street' => 'K-H St, Kamias Rd',
                'barangay' => 'Diliman',
                'city' => 'Quezon City',
                'state' => 'Metro Manila',
                'contact' => '123456789',
                'note' => NULL,
                'table_no' => '2',
                'status' => 1,
                'created_at' => '2018-03-06 16:50:47',
                'updated_at' => '2018-03-06 16:50:47',
            ),
        ));
        
        
    }
}