<?php

use Illuminate\Database\Seeder;

class OrderProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('order_products')->delete();
        
        \DB::table('order_products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'order_id' => 1,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-11-23',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 11:23:15',
                'updated_at' => '2017-11-24 12:15:48',
            ),
            1 => 
            array (
                'id' => 2,
                'order_id' => 1,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-11-23',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 11:23:15',
                'updated_at' => '2017-11-24 12:16:05',
            ),
            2 => 
            array (
                'id' => 3,
                'order_id' => 1,
                'product_id' => 79,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 395.0,
                'total' => 395.0,
                'pickup_location' => '3',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 11:23:15',
                'updated_at' => '2017-11-24 12:16:13',
            ),
            3 => 
            array (
                'id' => 4,
                'order_id' => 1,
                'product_id' => 27,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 838.0,
                'total' => 838.0,
                'pickup_location' => '4',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 11:23:15',
                'updated_at' => '2017-11-24 12:16:54',
            ),
            4 => 
            array (
                'id' => 5,
                'order_id' => 1,
                'product_id' => 77,
                'provider_id' => 1,
                'quantity' => 2,
                'price' => 410.0,
                'total' => 820.0,
                'pickup_location' => '5',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 11:23:15',
                'updated_at' => '2017-11-24 11:23:15',
            ),
            5 => 
            array (
                'id' => 6,
                'order_id' => 1,
                'product_id' => 82,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 340.0,
                'total' => 340.0,
                'pickup_location' => '6',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 11:23:15',
                'updated_at' => '2017-11-24 11:23:15',
            ),
            6 => 
            array (
                'id' => 7,
                'order_id' => 2,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '7',
                'pickup_date' => '2017-11-23',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-22 11:23:15',
                'updated_at' => '2017-11-22 12:15:48',
            ),
            7 => 
            array (
                'id' => 8,
                'order_id' => 2,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '8',
                'pickup_date' => '2017-11-23',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-22 11:23:15',
                'updated_at' => '2017-11-22 11:23:15',
            ),
            8 => 
            array (
                'id' => 9,
                'order_id' => 2,
                'product_id' => 79,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 395.0,
                'total' => 395.0,
                'pickup_location' => '10',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-22 11:23:15',
                'updated_at' => '2017-11-22 11:23:15',
            ),
            9 => 
            array (
                'id' => 10,
                'order_id' => 2,
                'product_id' => 27,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 838.0,
                'total' => 838.0,
                'pickup_location' => '9',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-22 11:23:15',
                'updated_at' => '2017-11-22 11:23:15',
            ),
            10 => 
            array (
                'id' => 11,
                'order_id' => 2,
                'product_id' => 77,
                'provider_id' => 1,
                'quantity' => 2,
                'price' => 410.0,
                'total' => 820.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-22 11:23:15',
                'updated_at' => '2017-11-22 11:23:15',
            ),
            11 => 
            array (
                'id' => 12,
                'order_id' => 2,
                'product_id' => 82,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 340.0,
                'total' => 340.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-22 11:23:15',
                'updated_at' => '2017-11-22 11:23:15',
            ),
            12 => 
            array (
                'id' => 13,
                'order_id' => 3,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 17:07:12',
                'updated_at' => '2017-11-24 17:07:12',
            ),
            13 => 
            array (
                'id' => 14,
                'order_id' => 3,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 17:07:12',
                'updated_at' => '2017-11-24 17:07:12',
            ),
            14 => 
            array (
                'id' => 15,
                'order_id' => 3,
                'product_id' => 20,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1168.0,
                'total' => 1168.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 17:07:12',
                'updated_at' => '2017-11-24 17:07:12',
            ),
            15 => 
            array (
                'id' => 16,
                'order_id' => 3,
                'product_id' => 17,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 17:07:12',
                'updated_at' => '2017-11-24 17:07:12',
            ),
            16 => 
            array (
                'id' => 17,
                'order_id' => 4,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 17:10:12',
                'updated_at' => '2017-11-24 17:10:12',
            ),
            17 => 
            array (
                'id' => 18,
                'order_id' => 4,
                'product_id' => 98,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 540.0,
                'total' => 540.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 17:10:12',
                'updated_at' => '2017-11-24 17:10:12',
            ),
            18 => 
            array (
                'id' => 19,
                'order_id' => 4,
                'product_id' => 97,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 420.0,
                'total' => 420.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-11-24',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 3,
                'created_at' => '2017-11-24 17:10:12',
                'updated_at' => '2017-11-24 17:10:12',
            ),
            19 => 
            array (
                'id' => 20,
                'order_id' => 5,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-06',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-07 06:32:48',
                'updated_at' => '2017-12-07 06:32:48',
            ),
            20 => 
            array (
                'id' => 21,
                'order_id' => 5,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-06',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-07 06:32:48',
                'updated_at' => '2017-12-07 06:32:48',
            ),
            21 => 
            array (
                'id' => 22,
                'order_id' => 5,
                'product_id' => 17,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-06',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-07 06:32:48',
                'updated_at' => '2017-12-07 06:32:48',
            ),
            22 => 
            array (
                'id' => 23,
                'order_id' => 6,
                'product_id' => 17,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-08',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-09 01:26:46',
                'updated_at' => '2017-12-12 02:01:39',
            ),
            23 => 
            array (
                'id' => 24,
                'order_id' => 6,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-08',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-09 01:26:46',
                'updated_at' => '2017-12-12 02:01:39',
            ),
            24 => 
            array (
                'id' => 25,
                'order_id' => 7,
                'product_id' => 17,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-08',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-11 23:53:24',
                'updated_at' => '2017-12-11 23:53:24',
            ),
            25 => 
            array (
                'id' => 26,
                'order_id' => 7,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-08',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-11 23:53:24',
                'updated_at' => '2017-12-11 23:53:24',
            ),
            26 => 
            array (
                'id' => 27,
                'order_id' => 7,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-11 23:53:25',
                'updated_at' => '2017-12-11 23:53:25',
            ),
            27 => 
            array (
                'id' => 28,
                'order_id' => 8,
                'product_id' => 66,
                'provider_id' => 11,
                'quantity' => 1,
                'price' => 200.0,
                'total' => 200.0,
                'pickup_location' => '10',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-12 01:44:40',
                'updated_at' => '2017-12-12 01:44:40',
            ),
            28 => 
            array (
                'id' => 29,
                'order_id' => 9,
                'product_id' => 72,
                'provider_id' => 11,
                'quantity' => 1,
                'price' => 180.0,
                'total' => 180.0,
                'pickup_location' => '10',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-12 01:47:11',
                'updated_at' => '2017-12-23 04:41:51',
            ),
            29 => 
            array (
                'id' => 30,
                'order_id' => 10,
                'product_id' => 17,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-12 01:58:24',
                'updated_at' => '2017-12-12 01:58:24',
            ),
            30 => 
            array (
                'id' => 31,
                'order_id' => 10,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 2,
                'price' => 1143.0,
                'total' => 2286.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-12 01:58:25',
                'updated_at' => '2017-12-12 01:58:25',
            ),
            31 => 
            array (
                'id' => 32,
                'order_id' => 11,
                'product_id' => 137,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 150.0,
                'total' => 150.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 1,
                'created_at' => '2017-12-12 02:01:01',
                'updated_at' => '2017-12-13 23:48:52',
            ),
            32 => 
            array (
                'id' => 33,
                'order_id' => 11,
                'product_id' => 136,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 150.0,
                'total' => 150.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-12 02:01:01',
                'updated_at' => '2017-12-13 23:48:10',
            ),
            33 => 
            array (
                'id' => 34,
                'order_id' => 12,
                'product_id' => 137,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 150.0,
                'total' => 150.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 5,
                'created_at' => '2017-12-12 02:12:01',
                'updated_at' => '2017-12-14 03:48:35',
            ),
            34 => 
            array (
                'id' => 35,
                'order_id' => 12,
                'product_id' => 138,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 150.0,
                'total' => 150.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 1,
                'created_at' => '2017-12-12 02:12:01',
                'updated_at' => '2017-12-14 03:11:49',
            ),
            35 => 
            array (
                'id' => 36,
                'order_id' => 13,
                'product_id' => 45,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 290.0,
                'total' => 290.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-12 02:23:54',
                'updated_at' => '2017-12-12 02:23:54',
            ),
            36 => 
            array (
                'id' => 37,
                'order_id' => 14,
                'product_id' => 20,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1168.0,
                'total' => 1168.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-12 02:29:39',
                'updated_at' => '2017-12-12 02:29:39',
            ),
            37 => 
            array (
                'id' => 38,
                'order_id' => 15,
                'product_id' => 17,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-12 03:45:05',
                'updated_at' => '2017-12-12 03:45:05',
            ),
            38 => 
            array (
                'id' => 39,
                'order_id' => 16,
                'product_id' => 69,
                'provider_id' => 11,
                'quantity' => 1,
                'price' => 175.0,
                'total' => 175.0,
                'pickup_location' => '10',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-12 04:02:42',
                'updated_at' => '2017-12-12 04:02:42',
            ),
            39 => 
            array (
                'id' => 40,
                'order_id' => 17,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-12 04:04:28',
                'updated_at' => '2017-12-12 04:05:05',
            ),
            40 => 
            array (
                'id' => 41,
                'order_id' => 19,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-12 04:09:26',
                'updated_at' => '2017-12-12 04:09:26',
            ),
            41 => 
            array (
                'id' => 42,
                'order_id' => 19,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-12 04:09:26',
                'updated_at' => '2017-12-12 04:09:26',
            ),
            42 => 
            array (
                'id' => 43,
                'order_id' => 20,
                'product_id' => 72,
                'provider_id' => 11,
                'quantity' => 1,
                'price' => 180.0,
                'total' => 180.0,
                'pickup_location' => '10',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-12 05:13:54',
                'updated_at' => '2017-12-12 05:13:54',
            ),
            43 => 
            array (
                'id' => 44,
                'order_id' => 21,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-11',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-13 05:03:53',
                'updated_at' => '2017-12-13 05:04:06',
            ),
            44 => 
            array (
                'id' => 45,
                'order_id' => 21,
                'product_id' => 17,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-12',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-13 05:03:53',
                'updated_at' => '2017-12-13 05:04:06',
            ),
            45 => 
            array (
                'id' => 46,
                'order_id' => 21,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-12',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-13 05:03:53',
                'updated_at' => '2017-12-13 05:04:06',
            ),
            46 => 
            array (
                'id' => 47,
                'order_id' => 22,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-12',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-13 05:05:07',
                'updated_at' => '2017-12-13 05:05:28',
            ),
            47 => 
            array (
                'id' => 48,
                'order_id' => 23,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-12',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-13 23:09:00',
                'updated_at' => '2017-12-14 03:21:24',
            ),
            48 => 
            array (
                'id' => 49,
                'order_id' => 24,
                'product_id' => 20,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1168.0,
                'total' => 1168.0,
                'pickup_location' => '1',
                'pickup_date' => '2018-06-13',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 2,
                'created_at' => '2017-12-14 01:04:28',
                'updated_at' => '2017-12-14 01:04:54',
            ),
            49 => 
            array (
                'id' => 50,
                'order_id' => 25,
                'product_id' => 139,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 150.0,
                'total' => 150.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-13',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-14 01:07:55',
                'updated_at' => '2017-12-14 04:00:12',
            ),
            50 => 
            array (
                'id' => 51,
                'order_id' => 25,
                'product_id' => 138,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 150.0,
                'total' => 150.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-13',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-14 01:07:56',
                'updated_at' => '2018-01-09 23:26:43',
            ),
            51 => 
            array (
                'id' => 52,
                'order_id' => 26,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-13',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-14 03:22:23',
                'updated_at' => '2017-12-14 03:22:24',
            ),
            52 => 
            array (
                'id' => 53,
                'order_id' => 27,
                'product_id' => 20,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1168.0,
                'total' => 1168.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-13',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-14 03:40:18',
                'updated_at' => '2017-12-14 03:40:18',
            ),
            53 => 
            array (
                'id' => 54,
                'order_id' => 28,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-14',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 5,
                'created_at' => '2017-12-14 03:41:07',
                'updated_at' => '2017-12-14 03:48:34',
            ),
            54 => 
            array (
                'id' => 55,
                'order_id' => 29,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-13',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2017-12-14 03:51:43',
                'updated_at' => '2017-12-14 03:51:43',
            ),
            55 => 
            array (
                'id' => 56,
                'order_id' => 30,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-14',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-14 03:52:49',
                'updated_at' => '2017-12-22 04:16:27',
            ),
            56 => 
            array (
                'id' => 57,
                'order_id' => 31,
                'product_id' => 143,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 110.0,
                'total' => 110.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-13',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-14 04:48:46',
                'updated_at' => '2017-12-14 04:48:47',
            ),
            57 => 
            array (
                'id' => 58,
                'order_id' => 32,
                'product_id' => 136,
                'provider_id' => 4,
                'quantity' => 2,
                'price' => 150.0,
                'total' => 300.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-13',
                'pickup_time' => '06:00 PM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-14 06:29:35',
                'updated_at' => '2018-01-09 23:26:33',
            ),
            58 => 
            array (
                'id' => 59,
                'order_id' => 33,
                'product_id' => 141,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 90.0,
                'total' => 90.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-14',
                'pickup_time' => '02:00 PM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-15 01:08:44',
                'updated_at' => '2017-12-22 04:16:27',
            ),
            59 => 
            array (
                'id' => 60,
                'order_id' => 34,
                'product_id' => 140,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 80.0,
                'total' => 80.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-14',
                'pickup_time' => '12:00 NN',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-15 01:55:34',
                'updated_at' => '2017-12-15 01:55:36',
            ),
            60 => 
            array (
                'id' => 61,
                'order_id' => 35,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-09-18',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-20 01:34:30',
                'updated_at' => '2017-12-22 04:16:27',
            ),
            61 => 
            array (
                'id' => 62,
                'order_id' => 36,
                'product_id' => 20,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1168.0,
                'total' => 1168.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-21',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-22 07:50:59',
                'updated_at' => '2017-12-23 04:30:49',
            ),
            62 => 
            array (
                'id' => 63,
                'order_id' => 36,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-21',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-22 07:51:00',
                'updated_at' => '2017-12-23 04:30:49',
            ),
            63 => 
            array (
                'id' => 64,
                'order_id' => 36,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 2,
                'price' => 1143.0,
                'total' => 2286.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-21',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-22 07:51:00',
                'updated_at' => '2017-12-23 04:30:49',
            ),
            64 => 
            array (
                'id' => 65,
                'order_id' => 37,
                'product_id' => 142,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 110.0,
                'total' => 110.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-21',
                'pickup_time' => '06:00 PM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-22 07:54:55',
                'updated_at' => '2017-12-22 07:54:56',
            ),
            65 => 
            array (
                'id' => 66,
                'order_id' => 38,
                'product_id' => 21,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1371.0,
                'total' => 1371.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-21',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-22 08:02:32',
                'updated_at' => '2017-12-23 04:30:49',
            ),
            66 => 
            array (
                'id' => 67,
                'order_id' => 39,
                'product_id' => 142,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 110.0,
                'total' => 110.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-21',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-22 08:05:51',
                'updated_at' => '2017-12-22 08:05:52',
            ),
            67 => 
            array (
                'id' => 68,
                'order_id' => 40,
                'product_id' => 142,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 110.0,
                'total' => 110.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-21',
                'pickup_time' => '06:00 PM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-22 08:33:08',
                'updated_at' => '2018-01-09 23:26:20',
            ),
            68 => 
            array (
                'id' => 69,
                'order_id' => 41,
                'product_id' => 136,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 150.0,
                'total' => 150.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-22',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-23 04:25:19',
                'updated_at' => '2017-12-23 04:45:14',
            ),
            69 => 
            array (
                'id' => 70,
                'order_id' => 42,
                'product_id' => 143,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 110.0,
                'total' => 110.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-22',
                'pickup_time' => '06:00 PM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2017-12-23 04:38:19',
                'updated_at' => '2017-12-28 03:47:11',
            ),
            70 => 
            array (
                'id' => 71,
                'order_id' => 43,
                'product_id' => 155,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 150.0,
                'total' => 150.0,
                'pickup_location' => '2',
                'pickup_date' => '2018-01-03',
                'pickup_time' => '11:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2018-01-03 23:28:12',
                'updated_at' => '2018-01-04 00:01:40',
            ),
            71 => 
            array (
                'id' => 72,
                'order_id' => 46,
                'product_id' => 154,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 150.0,
                'total' => 150.0,
                'pickup_location' => '2',
                'pickup_date' => '2018-01-03',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2018-01-04 05:37:45',
                'updated_at' => '2018-01-04 05:37:54',
            ),
            72 => 
            array (
                'id' => 73,
                'order_id' => 47,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 5,
                'price' => 1143.0,
                'total' => 5715.0,
                'pickup_location' => '1',
                'pickup_date' => '2017-12-21',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2018-01-04 22:17:47',
                'updated_at' => '2018-01-04 22:17:47',
            ),
            73 => 
            array (
                'id' => 74,
                'order_id' => 48,
                'product_id' => 20,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1168.0,
                'total' => 1168.0,
                'pickup_location' => '1',
                'pickup_date' => '2018-01-04',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2018-01-05 00:23:23',
                'updated_at' => '2018-01-05 00:23:23',
            ),
            74 => 
            array (
                'id' => 75,
                'order_id' => 49,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2018-01-04',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2018-01-05 01:46:06',
                'updated_at' => '2018-01-05 01:46:06',
            ),
            75 => 
            array (
                'id' => 76,
                'order_id' => 50,
                'product_id' => 23,
                'provider_id' => 1,
                'quantity' => 2,
                'price' => 1315.0,
                'total' => 2630.0,
                'pickup_location' => '1',
                'pickup_date' => '2018-01-04',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2018-01-05 02:08:39',
                'updated_at' => '2018-01-05 02:08:43',
            ),
            76 => 
            array (
                'id' => 77,
                'order_id' => 51,
                'product_id' => 19,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1011.0,
                'total' => 1011.0,
                'pickup_location' => '1',
                'pickup_date' => '2018-01-04',
                'pickup_time' => '02:00 PM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2018-01-05 02:10:36',
                'updated_at' => '2018-01-11 03:56:19',
            ),
            77 => 
            array (
                'id' => 78,
                'order_id' => 52,
                'product_id' => 156,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 130.0,
                'total' => 130.0,
                'pickup_location' => '2',
                'pickup_date' => '2017-12-28',
                'pickup_time' => '12:00 NN',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2018-01-05 06:47:29',
                'updated_at' => '2018-01-05 06:49:48',
            ),
            78 => 
            array (
                'id' => 79,
                'order_id' => 53,
                'product_id' => 23,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1315.0,
                'total' => 1315.0,
                'pickup_location' => '1',
                'pickup_date' => '2018-01-04',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2018-01-05 06:54:35',
                'updated_at' => '2018-01-05 06:54:35',
            ),
            79 => 
            array (
                'id' => 80,
                'order_id' => 55,
                'product_id' => 150,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 120.0,
                'total' => 120.0,
                'pickup_location' => '2',
                'pickup_date' => '2018-01-04',
                'pickup_time' => '06:00 PM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2018-01-05 06:58:58',
                'updated_at' => '2018-01-05 07:00:02',
            ),
            80 => 
            array (
                'id' => 81,
                'order_id' => 57,
                'product_id' => 20,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1168.0,
                'total' => 1168.0,
                'pickup_location' => '1',
                'pickup_date' => '2018-01-04',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2018-01-05 07:19:43',
                'updated_at' => '2018-01-11 03:56:19',
            ),
            81 => 
            array (
                'id' => 82,
                'order_id' => 59,
                'product_id' => 24,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1102.0,
                'total' => 1102.0,
                'pickup_location' => '1',
                'pickup_date' => '2018-01-04',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2018-01-05 07:20:27',
                'updated_at' => '2018-01-11 03:56:19',
            ),
            82 => 
            array (
                'id' => 83,
                'order_id' => 60,
                'product_id' => 151,
                'provider_id' => 4,
                'quantity' => 1,
                'price' => 100.0,
                'total' => 100.0,
                'pickup_location' => '2',
                'pickup_date' => '0000-00-00',
                'pickup_time' => '06:00 PM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2018-01-06 06:23:57',
                'updated_at' => '2018-01-09 23:25:48',
            ),
            83 => 
            array (
                'id' => 84,
                'order_id' => 61,
                'product_id' => 18,
                'provider_id' => 1,
                'quantity' => 1,
                'price' => 1143.0,
                'total' => 1143.0,
                'pickup_location' => '1',
                'pickup_date' => '2018-02-01',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 4,
                'created_at' => '2018-02-01 05:15:02',
                'updated_at' => '2018-02-12 11:16:06',
            ),
            84 => 
            array (
                'id' => 85,
                'order_id' => 62,
                'product_id' => 69,
                'provider_id' => 11,
                'quantity' => 1,
                'price' => 175.0,
                'total' => 175.0,
                'pickup_location' => '10',
                'pickup_date' => '2018-03-07',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2018-03-06 16:43:56',
                'updated_at' => '2018-03-06 16:43:56',
            ),
            85 => 
            array (
                'id' => 86,
                'order_id' => 63,
                'product_id' => 73,
                'provider_id' => 11,
                'quantity' => 1,
                'price' => 180.0,
                'total' => 180.0,
                'pickup_location' => '10',
                'pickup_date' => '2018-03-07',
                'pickup_time' => '9:00 AM',
                'note' => NULL,
                'progress' => 0,
                'status' => 0,
                'created_at' => '2018-03-06 16:50:02',
                'updated_at' => '2018-03-06 16:50:02',
            ),
        ));
        
        
    }
}