<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 17,
                'picture' => '17.jpg',
                'provider_id' => 1,
                'category_id' => 6,
                'name' => 'Baked Blueberry Cheesecake',
                'price' => 1143.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Baked Blueberry Cheesecake',
                'day_start' => '2017-10-06',
                'day_end' => '2017-10-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 18,
                'picture' => '18.jpg',
                'provider_id' => 1,
                'category_id' => 6,
                'name' => 'Baked Strawberry Cheesecake',
                'price' => 1143.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Baked Strawberry Cheesecake',
                'day_start' => '2017-10-06',
                'day_end' => '2017-10-09',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 19,
                'picture' => '19.jpg',
                'provider_id' => 1,
                'category_id' => 3,
                'name' => 'Black Forest',
                'price' => 1011.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Black Forest',
                'day_start' => '2017-10-06',
                'day_end' => '2017-10-16',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 20,
                'picture' => '20.jpg',
                'provider_id' => 1,
                'category_id' => 3,
                'name' => 'Carrot Cake',
                'price' => 1168.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Carrot Cake',
                'day_start' => '2017-10-06',
                'day_end' => '2017-10-16',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 21,
                'picture' => '21.jpg',
                'provider_id' => 1,
                'category_id' => 3,
                'name' => 'Cherry Walnut',
                'price' => 1371.0,
                'qty' => 1371,
                'sale_price' => NULL,
                'description' => 'Cherry Walnut',
                'day_start' => '2017-10-06',
                'day_end' => '2017-10-17',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 22,
                'picture' => '22.jpg',
                'provider_id' => 1,
                'category_id' => 3,
                'name' => 'Chocolate Caramel',
                'price' => 1169.0,
                'qty' => 0,
                'sale_price' => NULL,
                'description' => 'Chocolate Caramel',
                'day_start' => '2017-10-06',
                'day_end' => '2017-10-15',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 23,
                'picture' => '23.jpg',
                'provider_id' => 1,
                'category_id' => 3,
                'name' => 'DARK BELGIAN CAKE',
                'price' => 1315.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'DARK BELGIAN CAKE',
                'day_start' => '2017-10-06',
                'day_end' => '2017-10-16',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 24,
                'picture' => '24.jpg',
                'provider_id' => 1,
                'category_id' => 3,
                'name' => 'Devils Cake',
                'price' => 1102.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Devils Cake',
                'day_start' => '2017-10-06',
                'day_end' => '2017-10-16',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 26,
                'picture' => '26.jpg',
                'provider_id' => 1,
                'category_id' => 3,
                'name' => 'Double Chocolate',
                'price' => 1168.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Double Chocolate',
                'day_start' => '2017-10-06',
                'day_end' => '2017-10-16',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 27,
                'picture' => '27.jpg',
                'provider_id' => 1,
                'category_id' => 3,
                'name' => 'Dulce de Leche',
                'price' => 838.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Dulce de Leche',
                'day_start' => '2017-10-06',
                'day_end' => '2017-10-16',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 28,
                'picture' => '28.jpg',
                'provider_id' => 1,
                'category_id' => 3,
                'name' => 'Loacker Chocolate Cheesecake',
                'price' => 1011.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Loacker Chocolate Cheesecake',
                'day_start' => '2017-10-06',
                'day_end' => '2017-10-16',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 45,
                'picture' => '45.jpg',
                'provider_id' => 1,
                'category_id' => 8,
                'name' => 'Chorizo Fettucine',
                'price' => 290.0,
                'qty' => 0,
                'sale_price' => NULL,
                'description' => 'Chorizo Fettucine',
                'day_start' => '0000-00-00',
                'day_end' => '0000-00-00',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 47,
                'picture' => '47.jpg',
                'provider_id' => 2,
                'category_id' => 8,
                'name' => 'All Meat Platter',
                'price' => 1090.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'All Meat Platter from C2',
                'day_start' => '2017-10-09',
                'day_end' => '2018-01-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 48,
                'picture' => '48.jpg',
                'provider_id' => 1,
                'category_id' => 13,
                'name' => 'Classic Meatballs Spaghetti',
                'price' => 320.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Classic Meatballs Spaghetti',
                'day_start' => '2017-10-09',
                'day_end' => '2017-10-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 51,
                'picture' => '51.jpg',
                'provider_id' => 1,
                'category_id' => 13,
                'name' => 'Creamy Baked Macaroni',
                'price' => 290.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Creamy Baked Macaroni',
                'day_start' => '2017-10-10',
                'day_end' => '2017-10-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 52,
                'picture' => '52.jpg',
                'provider_id' => 1,
                'category_id' => 13,
                'name' => 'Fettucine Stroganoff',
                'price' => 390.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Fettucine Stroganoff',
                'day_start' => '2017-10-09',
                'day_end' => '2017-10-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 53,
                'picture' => '53.jpg',
                'provider_id' => 2,
                'category_id' => 10,
                'name' => 'Bagoong Rice',
                'price' => 135.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Bagoong Rice from C2',
                'day_start' => '2017-10-09',
                'day_end' => '2017-10-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 54,
                'picture' => '54.jpg',
                'provider_id' => 1,
                'category_id' => 4,
                'name' => 'French Onion Soup Gratinee',
                'price' => 150.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'French Onion Soup Gratinee',
                'day_start' => '2017-10-09',
                'day_end' => '2017-10-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 55,
                'picture' => '55.jpg',
                'provider_id' => 1,
                'category_id' => 13,
                'name' => 'Four Cheese Lasagna',
                'price' => 340.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Four Cheese Lasagna',
                'day_start' => '2017-10-09',
                'day_end' => '2017-10-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 56,
                'picture' => '56.jpg',
                'provider_id' => 1,
                'category_id' => 8,
                'name' => 'House Premium Burger',
                'price' => 350.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'House Premium Burger',
                'day_start' => '2017-10-09',
                'day_end' => '2017-10-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 57,
                'picture' => '57.jpg',
                'provider_id' => 2,
                'category_id' => 6,
                'name' => 'Bibingka Souffle',
                'price' => 175.0,
                'qty' => 12,
                'sale_price' => NULL,
                'description' => 'Bibingka Souffle from C2',
                'day_start' => '2017-10-09',
                'day_end' => '2018-02-28',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 58,
                'picture' => '58.jpg',
                'provider_id' => 2,
                'category_id' => 8,
                'name' => 'Binagoongan Lechon Kawali',
                'price' => 415.0,
                'qty' => 15,
                'sale_price' => NULL,
                'description' => 'Binagoongan Lechon Kawali from C2',
                'day_start' => '2017-10-30',
                'day_end' => '2017-12-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 59,
                'picture' => '59.jpg',
                'provider_id' => 2,
                'category_id' => 5,
                'name' => 'Buko Pandan',
                'price' => 155.0,
                'qty' => 25,
                'sale_price' => NULL,
                'description' => 'Buko Pandan from C2',
                'day_start' => '2017-10-09',
                'day_end' => '2018-04-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 60,
                'picture' => '60.jpg',
                'provider_id' => 2,
                'category_id' => 9,
                'name' => 'Bulalo',
                'price' => 495.0,
                'qty' => 50,
                'sale_price' => NULL,
                'description' => 'Bulalo from C2',
                'day_start' => '2017-10-09',
                'day_end' => '2017-10-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 61,
                'picture' => '61.jpg',
                'provider_id' => 2,
                'category_id' => 12,
                'name' => 'Chicharong Munggo with Galunggong',
                'price' => 280.0,
                'qty' => 280,
                'sale_price' => NULL,
                'description' => 'Chicharong Munggo with Galunggong from C2',
                'day_start' => '2017-10-09',
                'day_end' => '2017-12-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 62,
                'picture' => '62.jpg',
                'provider_id' => 2,
                'category_id' => 8,
                'name' => 'Crispy Kare Kare',
                'price' => 780.0,
                'qty' => 780,
                'sale_price' => NULL,
                'description' => 'Crispy Kare Kare from C2',
                'day_start' => '2017-10-09',
                'day_end' => '2018-07-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 63,
                'picture' => '63.jpg',
                'provider_id' => 2,
                'category_id' => 10,
                'name' => 'Dagat Platter',
                'price' => 1090.0,
                'qty' => 1090,
                'sale_price' => NULL,
                'description' => 'Dagat Platter from C2',
                'day_start' => '2017-10-09',
                'day_end' => '2018-01-31',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 64,
                'picture' => '64.jpg',
                'provider_id' => 2,
                'category_id' => 10,
                'name' => 'Gising Gising',
                'price' => 285.0,
                'qty' => 285,
                'sale_price' => NULL,
                'description' => 'Gising Gising by C2',
                'day_start' => '2017-10-10',
                'day_end' => '2018-01-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 65,
                'picture' => '65.jpg',
                'provider_id' => 1,
                'category_id' => 8,
                'name' => 'Binagoongan',
                'price' => 150.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Pork Binagoongan',
                'day_start' => '2017-11-01',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 66,
                'picture' => '66.jpg',
                'provider_id' => 11,
                'category_id' => 8,
                'name' => 'Arroz Ala Cubana',
                'price' => 200.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Pork Dish',
                'day_start' => '2017-11-08',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 67,
                'picture' => '67.jpg',
                'provider_id' => 11,
                'category_id' => 6,
                'name' => 'Chocolate Caramel Brownies',
                'price' => 99.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Chocolate Caramel Brownies',
                'day_start' => '2017-11-01',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 68,
                'picture' => '68.jpg',
                'provider_id' => 11,
                'category_id' => 10,
                'name' => 'Garlic Bangus',
                'price' => 185.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Fish Dish',
                'day_start' => '2017-11-09',
                'day_end' => '2017-12-01',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 69,
                'picture' => '69.jpg',
                'provider_id' => 11,
                'category_id' => 9,
                'name' => 'Beef Tapa',
                'price' => 175.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Beef Dish',
                'day_start' => '2017-11-08',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 70,
                'picture' => '70.jpg',
                'provider_id' => 11,
                'category_id' => 7,
                'name' => 'Chicken Inasal',
                'price' => 180.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Grilled Chicken',
                'day_start' => '2017-11-08',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 71,
                'picture' => '71.jpg',
                'provider_id' => 11,
                'category_id' => 7,
                'name' => 'Chicken Teriyaki',
                'price' => 185.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Chicken Dish with Teriyaki Sauce',
                'day_start' => '2017-11-08',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 72,
                'picture' => '72.jpg',
                'provider_id' => 11,
                'category_id' => 9,
                'name' => 'Corned Beef',
                'price' => 180.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'House made corned beef',
                'day_start' => '2017-11-08',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 73,
                'picture' => '73.jpg',
                'provider_id' => 11,
                'category_id' => 8,
                'name' => 'Menudo',
                'price' => 180.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Pork in tomato sauce dish',
                'day_start' => '2017-11-08',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 74,
                'picture' => '74.jpg',
                'provider_id' => 11,
                'category_id' => 13,
                'name' => 'Bolognese',
                'price' => 175.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Pasta Dish',
                'day_start' => '2017-11-08',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 75,
                'picture' => '75.jpg',
                'provider_id' => 11,
                'category_id' => 10,
                'name' => 'Tuna Sandwich',
                'price' => 95.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Tuna Sandwich Dish',
                'day_start' => '2017-11-08',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 76,
                'picture' => '76.jpg',
                'provider_id' => 1,
                'category_id' => 10,
                'name' => 'Almond Crusted Fish Fillet',
                'price' => 420.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Almond Crusted Fish Fillet by Cravings Katipunan',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 77,
                'picture' => '77.jpg',
                'provider_id' => 1,
                'category_id' => 8,
                'name' => 'American Baked Ribs',
                'price' => 410.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'American Baked Ribs by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 78,
                'picture' => '78.jpg',
                'provider_id' => 1,
                'category_id' => 10,
                'name' => 'Baked Fish Provencial',
                'price' => 400.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Baked Fish Provencial by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 79,
                'picture' => '79.jpg',
                'provider_id' => 1,
                'category_id' => 9,
                'name' => 'Beef Fajitas',
                'price' => 395.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Beef Fajitas by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 80,
                'picture' => '80.jpg',
                'provider_id' => 1,
                'category_id' => 8,
                'name' => 'Bistro Pork Steak',
                'price' => 360.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Bistro Pork Steak by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '1',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 81,
                'picture' => '81.jpg',
                'provider_id' => 1,
                'category_id' => 7,
                'name' => 'Chicken A La Pobre',
                'price' => 360.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Chicken A La Pobre by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 82,
                'picture' => '82.jpg',
                'provider_id' => 1,
                'category_id' => 13,
                'name' => 'Chicken and Pesto Penne',
                'price' => 340.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Chicken and Pesto Penne by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 83,
                'picture' => '83.jpg',
                'provider_id' => 1,
                'category_id' => 7,
                'name' => 'Chicken Cordon Bleu',
                'price' => 455.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Chicken Cordon Bleu by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 84,
                'picture' => '84.jpg',
                'provider_id' => 1,
                'category_id' => 7,
                'name' => 'Chicken Galantine',
                'price' => 385.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Chicken Galantine by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 85,
                'picture' => '85.jpg',
                'provider_id' => 1,
                'category_id' => 13,
                'name' => 'Chorizo Fettucine',
                'price' => 290.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Chorizo Fettucine by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 86,
                'picture' => '86.jpg',
                'provider_id' => 1,
                'category_id' => 13,
                'name' => 'Classic Meatballs Spaghetti',
                'price' => 320.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Classic Meatballs Spaghetti by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 87,
                'picture' => '87.jpg',
                'provider_id' => 1,
                'category_id' => 6,
                'name' => 'Cravings Club House',
                'price' => 350.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Cravings Club House by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 88,
                'picture' => '88.jpg',
                'provider_id' => 1,
                'category_id' => 10,
                'name' => 'Cravings Seafood Basket',
                'price' => 275.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Cravings Seafood Basket by Cravings',
                'day_start' => '2017-10-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 89,
                'picture' => '89.jpg',
                'provider_id' => 1,
                'category_id' => 13,
                'name' => 'Creamy Baked Macaroni',
                'price' => 290.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Creamy Baked Macaroni by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 90,
                'picture' => '90.jpg',
                'provider_id' => 3,
                'category_id' => 7,
                'name' => '3 Way Chick',
                'price' => 195.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => '3 Way Chick by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 91,
                'picture' => '91.jpg',
                'provider_id' => 1,
                'category_id' => 13,
                'name' => 'Fettucine Stroganoff',
                'price' => 390.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Fettucine Stroganoff by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 92,
                'picture' => '92.jpg',
                'provider_id' => 3,
                'category_id' => 7,
                'name' => 'A Game Fish Bun',
                'price' => 250.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'A Game Fish Bun by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 93,
                'picture' => '93.jpg',
                'provider_id' => 1,
                'category_id' => 13,
                'name' => 'Four Cheese Lasagna',
                'price' => 340.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Four Cheese Lasagna by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 94,
                'picture' => '94.jpg',
                'provider_id' => 1,
                'category_id' => 4,
                'name' => 'French Onion Soup Gratinee',
                'price' => 150.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'French Onion Soup Gratinee',
                'day_start' => '2017-11-10',
                'day_end' => '2017-10-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 95,
                'picture' => '95.jpg',
                'provider_id' => 3,
                'category_id' => 7,
                'name' => '3 Way Chick',
                'price' => 195.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => '3 Way Chick by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 96,
                'picture' => '96.jpg',
                'provider_id' => 1,
                'category_id' => 9,
                'name' => 'House Premium Burger',
                'price' => 350.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'House Premium Burger by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 97,
                'picture' => '97.jpg',
                'provider_id' => 1,
                'category_id' => 2,
                'name' => 'K-Pop Chicken',
                'price' => 420.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'K-Pop Chicken by Cravings',
                'day_start' => '2017-09-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 98,
                'picture' => '98.jpg',
                'provider_id' => 1,
                'category_id' => 2,
                'name' => 'Lengua Con Champignon',
                'price' => 540.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Lengua Con Champignon by Cravings',
                'day_start' => '2017-09-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 99,
                'picture' => '99.jpg',
                'provider_id' => 3,
                'category_id' => 10,
                'name' => 'A Game Fish',
                'price' => 250.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'A Game Fish by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 100,
                'picture' => '100.jpg',
                'provider_id' => 1,
                'category_id' => 6,
                'name' => 'Monte Cristo',
                'price' => 290.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Monte Cristo by Cravings',
                'day_start' => '2017-09-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 101,
                'picture' => '101.jpg',
                'provider_id' => 1,
                'category_id' => 2,
                'name' => 'Old School Beef Pot Roast',
                'price' => 450.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Old School Beef Pot Roast by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 102,
                'picture' => '102.jpg',
                'provider_id' => 3,
                'category_id' => 9,
                'name' => 'Bibimbowl',
                'price' => 225.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Bibimbowl by B&P ',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 103,
                'picture' => '103.jpg',
                'provider_id' => 1,
                'category_id' => 10,
                'name' => 'One Surf and Turf',
                'price' => 575.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'One Surf and Turf by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 104,
                'picture' => '104.jpg',
                'provider_id' => 3,
                'category_id' => 10,
                'name' => 'Bistek Bangus Belly',
                'price' => 250.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Bistek Bangus Belly by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-10-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 105,
                'picture' => '105.jpg',
                'provider_id' => 1,
                'category_id' => 2,
                'name' => 'Paella Filipina',
                'price' => 420.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Paella Filipina by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 106,
                'picture' => '106.jpg',
                'provider_id' => 3,
                'category_id' => 2,
                'name' => 'Burito Omelette',
                'price' => 260.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Burito Omelette by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 107,
                'picture' => '107.jpg',
                'provider_id' => 3,
                'category_id' => 13,
                'name' => 'Carbonara',
                'price' => 265.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Carbonara by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 108,
                'picture' => '108.jpg',
                'provider_id' => 1,
                'category_id' => 4,
                'name' => 'Pancit Molo',
                'price' => 165.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Pancit Molo by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 109,
                'picture' => '109.jpg',
                'provider_id' => 1,
                'category_id' => 6,
                'name' => 'Pot Roast Gravy Sandwich',
                'price' => 385.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Pot Roast Gravy Sandwich by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 110,
                'picture' => '110.jpg',
                'provider_id' => 3,
                'category_id' => 7,
                'name' => 'Chicken Parmigana',
                'price' => 280.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Chicken Parmigana by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 111,
                'picture' => '111.jpg',
                'provider_id' => 3,
                'category_id' => 7,
                'name' => 'Chicken Toast',
                'price' => 295.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Chicken Toast by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 112,
                'picture' => '112.jpg',
                'provider_id' => 1,
                'category_id' => 13,
                'name' => 'Spicy Shrimp Gamberetti',
                'price' => 360.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Spicy Shrimp Gamberetti by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 113,
                'picture' => '113.jpg',
                'provider_id' => 1,
                'category_id' => 2,
                'name' => 'Spring Rolls with Vermicelli',
                'price' => 160.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Spring Rolls with Vermicelli by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 114,
                'picture' => '114.jpg',
                'provider_id' => 3,
                'category_id' => 4,
                'name' => 'Chowder Soup',
                'price' => 145.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Chowder Soup by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 115,
                'picture' => '115.jpg',
                'provider_id' => 1,
                'category_id' => 2,
                'name' => 'Sunday Best Roast Chicken',
                'price' => 360.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Sunday Best Roast Chicken by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 116,
                'picture' => '116.jpg',
                'provider_id' => 3,
                'category_id' => 8,
                'name' => 'Don Malutong',
                'price' => 285.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Don Malutong by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 117,
                'picture' => '117.jpg',
                'provider_id' => 3,
                'category_id' => 2,
                'name' => 'Eggs in Purgatory',
                'price' => 195.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Eggs in Purgatory by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 118,
                'picture' => '118.jpg',
                'provider_id' => 1,
                'category_id' => 2,
                'name' => 'Tenderloin Tips',
                'price' => 480.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Tenderloin Tips by Cravings',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 119,
                'picture' => '119.jpg',
                'provider_id' => 3,
                'category_id' => 2,
                'name' => 'Go Hawaiian',
                'price' => 185.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Go Hawaiian by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 120,
                'picture' => '120.jpg',
                'provider_id' => 3,
                'category_id' => 1,
                'name' => 'Ice Cream Cookie Sandwich',
                'price' => 140.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Ice Cream Cookie Sandwich by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 121,
                'picture' => '121.jpg',
                'provider_id' => 3,
                'category_id' => 13,
                'name' => 'Killer Mac & Cheese',
                'price' => 195.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Killer Mac & Cheese by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 122,
                'picture' => '122.jpg',
                'provider_id' => 3,
                'category_id' => 7,
                'name' => 'Kimchicken',
                'price' => 295.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Kimchicken by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 123,
                'picture' => '123.jpg',
                'provider_id' => 3,
                'category_id' => 9,
                'name' => 'Mang Benedicts',
                'price' => 295.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Mang Benedicts by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 124,
                'picture' => '124.jpg',
                'provider_id' => 3,
                'category_id' => 13,
                'name' => 'Meatball Spaghetti',
                'price' => 195.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Meatball Spaghetti by B&P ',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 125,
                'picture' => '125.jpg',
                'provider_id' => 3,
                'category_id' => 8,
                'name' => 'Meatloaf Surprise',
                'price' => 285.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Meatloaf Surprise by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 126,
                'picture' => '126.jpg',
                'provider_id' => 3,
                'category_id' => 13,
                'name' => 'Pesto Chix',
                'price' => 295.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Pesto Chix by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 127,
                'picture' => '127.jpg',
                'provider_id' => 3,
                'category_id' => 9,
                'name' => 'Primera Tapa',
                'price' => 295.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Primera Tapa by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-10-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 128,
                'picture' => '128.jpg',
                'provider_id' => 3,
                'category_id' => 4,
                'name' => 'Red Molo Soup',
                'price' => 175.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Red Molo Soup by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 129,
                'picture' => '129.jpg',
                'provider_id' => 3,
                'category_id' => 2,
                'name' => 'So Young Chow',
                'price' => 220.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'So Young Chow by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 130,
                'picture' => '130.jpg',
                'provider_id' => 3,
                'category_id' => 8,
                'name' => 'Spam Aloha ',
                'price' => 285.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Spam Aloha by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 131,
                'picture' => '131.jpg',
                'provider_id' => 3,
                'category_id' => 8,
                'name' => 'Spam Aloha Kids',
                'price' => 285.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Spam Aloha Kids by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 132,
                'picture' => '132.jpg',
                'provider_id' => 3,
                'category_id' => 8,
                'name' => 'Spam Rice',
                'price' => 165.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Spam Rice by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 133,
                'picture' => '133.jpg',
                'provider_id' => 3,
                'category_id' => 8,
                'name' => 'Spam Super B',
                'price' => 245.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Spam Super B by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 134,
                'picture' => '134.jpg',
                'provider_id' => 3,
                'category_id' => 1,
                'name' => 'Toffee Pudding',
                'price' => 175.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Toffee Pudding by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 135,
                'picture' => '135.jpg',
                'provider_id' => 3,
                'category_id' => 4,
                'name' => 'Tomato Soup with Grilled Cheese',
                'price' => 225.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Tomato Soup with Grilled Cheese by B&P',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 136,
                'picture' => '136.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Blueberry Milkshake',
                'price' => 150.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Blueberry Milkshake by TCB',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 137,
                'picture' => '137.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Strawberry Milkshake',
                'price' => 150.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Strawberry Milkshake by TCB',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 138,
                'picture' => '138.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Mango Cheesecake Milkshake',
                'price' => 150.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Mango Cheesecake Milkshake by TCB',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 139,
                'picture' => '139.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Chocolate Caramel Milkshake',
                'price' => 150.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Chocolate Caramel Milkshake by TCB',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 140,
                'picture' => '140.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Espresso',
                'price' => 80.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Espresso by TCB',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 141,
                'picture' => '141.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Macchiato',
                'price' => 90.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Macchiato by TCB',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 142,
                'picture' => '142.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Cafe Latte',
                'price' => 110.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Cafe Latte by TCB',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 143,
                'picture' => '143.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Capuccino',
                'price' => 110.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Capuccino by TCB',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 144,
                'picture' => '144.jpg',
                'provider_id' => 5,
                'category_id' => 15,
                'name' => 'Espresso',
                'price' => 90.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Espresso by Where\'s Marcel?',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 145,
                'picture' => '145.jpg',
                'provider_id' => 5,
                'category_id' => 15,
                'name' => 'Macchiato',
                'price' => 110.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Macchiato by Where\'s Marcel?',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 146,
                'picture' => '146.jpg',
                'provider_id' => 5,
                'category_id' => 15,
                'name' => 'Piccolo',
                'price' => 120.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Piccolo by Where\'s Marcel?',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 147,
                'picture' => '147.jpg',
                'provider_id' => 5,
                'category_id' => 15,
                'name' => 'Long Black',
                'price' => 120.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Long Black by Where\'s Marcel?',
                'day_start' => '2017-11-10',
                'day_end' => '2017-10-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 148,
                'picture' => '148.jpg',
                'provider_id' => 5,
                'category_id' => 15,
                'name' => 'Cafe Latte',
                'price' => 150.0,
                'qty' => 10,
                'sale_price' => NULL,
                'description' => 'Cafe Latte by Where\'s Marcel?',
                'day_start' => '2017-11-10',
                'day_end' => '2017-11-30',
                'non_expiry' => 1,
                'delivery_type' => '0',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 150,
                'picture' => '1514348392.jpg',
                'provider_id' => 4,
                'category_id' => 16,
                'name' => 'Hot Choco',
                'price' => 120.0,
                'qty' => 1000,
                'sale_price' => NULL,
                'description' => 'Hot Choco by The Coffee Beanery',
                'day_start' => '2017-12-22',
                'day_end' => '2050-12-15',
                'non_expiry' => 1,
                'delivery_type' => '1',
                'status' => 1,
                'created_at' => '2017-12-23 05:43:14',
                'updated_at' => '2017-12-28 01:19:52',
            ),
            113 => 
            array (
                'id' => 151,
                'picture' => '1514348413.jpg',
                'provider_id' => 4,
                'category_id' => 16,
                'name' => 'Iced Tea',
                'price' => 100.0,
                'qty' => 1000,
                'sale_price' => NULL,
                'description' => 'Iced Tea by The Coffee Beanery',
                'day_start' => '2017-12-27',
                'day_end' => NULL,
                'non_expiry' => 1,
                'delivery_type' => '1',
                'status' => 1,
                'created_at' => '2017-12-27 22:55:12',
                'updated_at' => '2017-12-28 01:20:13',
            ),
            114 => 
            array (
                'id' => 152,
                'picture' => '1514348517.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Mocha',
                'price' => 150.0,
                'qty' => 1000,
                'sale_price' => NULL,
                'description' => 'Mocha by The Coffee Beanery',
                'day_start' => '2018-02-27',
                'day_end' => NULL,
                'non_expiry' => 1,
                'delivery_type' => '1',
                'status' => 1,
                'created_at' => '2017-12-27 23:02:23',
                'updated_at' => '2017-12-28 01:21:57',
            ),
            115 => 
            array (
                'id' => 153,
                'picture' => '1514343372.jpg',
                'provider_id' => 1,
                'category_id' => 3,
                'name' => 'asdasd',
                'price' => 1123.0,
                'qty' => 123,
                'sale_price' => NULL,
                'description' => 'asd',
                'day_start' => '2018-01-27',
                'day_end' => '2018-03-01',
                'non_expiry' => 1,
                'delivery_type' => '1',
                'status' => 0,
                'created_at' => '2017-12-27 23:30:07',
                'updated_at' => '2017-12-27 23:56:12',
            ),
            116 => 
            array (
                'id' => 154,
                'picture' => '1514429135.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Iced Spicy Mocha',
                'price' => 150.0,
                'qty' => 100,
                'sale_price' => NULL,
                'description' => 'Iced Spicy Mocha',
                'day_start' => NULL,
                'day_end' => NULL,
                'non_expiry' => 1,
                'delivery_type' => '1',
                'status' => 1,
                'created_at' => '2017-12-28 23:45:35',
                'updated_at' => '2017-12-28 23:45:35',
            ),
            117 => 
            array (
                'id' => 155,
                'picture' => '1514429350.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Chocnut Coffee',
                'price' => 150.0,
                'qty' => 1000,
                'sale_price' => NULL,
                'description' => 'Chocnut Coffee by The Coffee beanery',
                'day_start' => NULL,
                'day_end' => NULL,
                'non_expiry' => 1,
                'delivery_type' => '1',
                'status' => 1,
                'created_at' => '2017-12-28 23:49:10',
                'updated_at' => '2017-12-28 23:49:10',
            ),
            118 => 
            array (
                'id' => 156,
                'picture' => '1515036611.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Curly Tops Coffee',
                'price' => 130.0,
                'qty' => 100,
                'sale_price' => NULL,
                'description' => 'Curly Tops Coffee by The coffee Beanery',
                'day_start' => NULL,
                'day_end' => NULL,
                'non_expiry' => 1,
                'delivery_type' => '1',
                'status' => 1,
                'created_at' => '2018-01-05 00:30:11',
                'updated_at' => '2018-01-05 00:30:11',
            ),
            119 => 
            array (
                'id' => 157,
                'picture' => '1515037154.jpg',
                'provider_id' => 4,
                'category_id' => 15,
                'name' => 'Americano',
                'price' => 100.0,
                'qty' => 100,
                'sale_price' => NULL,
                'description' => 'American by The Coffee Beanery',
                'day_start' => NULL,
                'day_end' => NULL,
                'non_expiry' => 1,
                'delivery_type' => '1',
                'status' => 1,
                'created_at' => '2018-01-05 00:35:49',
                'updated_at' => '2018-01-05 00:39:14',
            ),
        ));
        
        
    }
}